#!/usr/bin/env bash
#
# Cross-compile the Nordstjernen engine (libnordstjernen) for iOS against a
# prebuilt dependency sysroot, and stage the static libraries + headers + a
# generated xcconfig that the Xcode host app (ios/App) links against.
#
# iOS runs the same GTK-free embeddable engine as Android (see meson.build's
# is_mobile): no GTK 4, gdk-pixbuf, librsvg, WebGL, audio/video helpers — just
# libnordstjernen driven by the UIKit shell in ios/App/.
#
# Prerequisites
# -------------
#   * macOS with the Xcode command-line tools (provides xcrun + the iOS SDK)
#   * meson + ninja on PATH
#   * A dependency sysroot holding the engine's native deps already cross-built
#     for the platform, with working .pc files. Point NORDSTJERNEN_IOS_SYSROOT
#     at it (base dir containing <platform>/lib/pkgconfig, or one platform
#     prefix directly). The sysroot is produced and published by the
#     nordstjernen-dependencies-build repo's ios/ build (fetch it with
#     ios/scripts/fetch-prebuilt-deps.sh). The required set mirrors Android:
#       glib-2.0, gobject-2.0, gio-2.0, gmodule-2.0, cairo, pango, pangocairo
#       (+ harfbuzz, freetype2, fontconfig, pixman, fribidi, libffi, pcre2,
#       expat, zlib, libpng), libcurl (+ openssl, nghttp2, brotli), sqlite3,
#       uchardet, libpsl, libwebp.
#
# Building that sysroot is the bulk of the porting work and is out of scope for
# this script; see ios/README.md for the current status.
#
# Usage:
#   NORDSTJERNEN_IOS_SYSROOT=~/.cache/nordstjernen-ios-sysroot \
#   ios/scripts/build-engine.sh device      # arm64 iphoneos
#   ios/scripts/build-engine.sh simulator   # arm64 iphonesimulator

set -euo pipefail

PLATFORM="${1:-device}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VENDOR="${REPO_ROOT}/ios/App/vendor"
MIN_IOS="15.0"

case "${PLATFORM}" in
  device)    IOS_SDK=iphoneos;        SUBSYSTEM=ios;           MIN_FLAG="-miphoneos-version-min=${MIN_IOS}" ;;
  simulator) IOS_SDK=iphonesimulator; SUBSYSTEM=ios-simulator; MIN_FLAG="-mios-simulator-version-min=${MIN_IOS}" ;;
  *) echo "usage: $0 [device|simulator]" >&2; exit 2 ;;
esac

command -v xcrun >/dev/null 2>&1 || { echo "xcrun not found — need Xcode CLT (macOS)" >&2; exit 2; }
command -v meson >/dev/null 2>&1 || { echo "meson not found" >&2; exit 2; }

SDKROOT="$(xcrun --sdk "${IOS_SDK}" --show-sdk-path)"
CLANG="$(xcrun --sdk "${IOS_SDK}" --find clang)"
CLANGXX="$(xcrun --sdk "${IOS_SDK}" --find clang++)"
AR="$(xcrun --sdk "${IOS_SDK}" --find ar)"
RANLIB="$(xcrun --sdk "${IOS_SDK}" --find ranlib)"
STRIP="$(xcrun --sdk "${IOS_SDK}" --find strip)"

# Resolve the dependency sysroot prefix for this platform.
SYSROOT_PREFIX=""
if [ -n "${NORDSTJERNEN_IOS_SYSROOT:-}" ]; then
  if [ -d "${NORDSTJERNEN_IOS_SYSROOT}/${PLATFORM}/lib/pkgconfig" ]; then
    SYSROOT_PREFIX="${NORDSTJERNEN_IOS_SYSROOT}/${PLATFORM}"
  else
    SYSROOT_PREFIX="${NORDSTJERNEN_IOS_SYSROOT}"
  fi
fi

WORK="${REPO_ROOT}/ios/.build/${PLATFORM}"
BUILDDIR="${WORK}/builddir"
CROSS="${WORK}/ios-${PLATFORM}.cross"
mkdir -p "${WORK}"

cat > "${CROSS}" <<EOF
# Auto-generated by ios/scripts/build-engine.sh — DO NOT EDIT BY HAND.
# iOS platform: ${PLATFORM}   SDK: ${IOS_SDK}   min: ${MIN_IOS}
[constants]
ios_args = ['-arch', 'arm64', '-isysroot', '${SDKROOT}', '${MIN_FLAG}']

[binaries]
c          = '${CLANG}'
cpp        = '${CLANGXX}'
ar         = '${AR}'
ranlib     = '${RANLIB}'
strip      = '${STRIP}'
pkg-config = 'pkg-config'

[built-in options]
c_args         = ios_args + ['-D_DARWIN_C_SOURCE']
cpp_args       = ios_args + ['-D_DARWIN_C_SOURCE']
c_link_args    = ios_args
cpp_link_args  = ios_args
default_library = 'static'

[properties]
pkg_config_libdir = '${SYSROOT_PREFIX}/lib/pkgconfig'
needs_exe_wrapper = true

[host_machine]
system     = 'darwin'
subsystem  = '${SUBSYSTEM}'
cpu_family = 'aarch64'
cpu        = 'aarch64'
endian     = 'little'
EOF

echo "Wrote cross file: ${CROSS}"
echo "iOS platform:     ${PLATFORM} (${IOS_SDK})"
echo "SDK:              ${SDKROOT}"
echo "Dependency sysroot: ${SYSROOT_PREFIX:-not set}"

if [ -z "${SYSROOT_PREFIX}" ] || [ ! -d "${SYSROOT_PREFIX}/lib/pkgconfig" ]; then
  cat >&2 <<MSG

NORDSTJERNEN_IOS_SYSROOT is not set (or has no lib/pkgconfig). The engine cannot
be cross-compiled without the dependency sysroot. The cross file was generated
at:
  ${CROSS}
Fetch the prebuilt sysroot (ios/scripts/fetch-prebuilt-deps.sh) or build it,
point NORDSTJERNEN_IOS_SYSROOT at it, and re-run.
MSG
  exit 0
fi

rm -rf "${BUILDDIR}"
meson setup "${BUILDDIR}" "${REPO_ROOT}" \
  --cross-file "${CROSS}" \
  --buildtype release \
  --default-library static \
  --wrap-mode nodownload \
  -Dios=true -Dgtk=disabled -Dai=disabled -Daudio=disabled \
  -Dpkg_config_path="${SYSROOT_PREFIX}/lib/pkgconfig"

meson compile -C "${BUILDDIR}"

# Stage headers, the engine + its in-tree static libs, and the sysroot deps.
DEST="${VENDOR}/${PLATFORM}"
rm -rf "${DEST}"
mkdir -p "${DEST}/lib" "${DEST}/include"
cp -f "${REPO_ROOT}/src/libnordstjernen.h" "${DEST}/include/"

# The static engine archive plus the in-tree static libs (lexbor, quickjs,
# wamr, wuffs, plmpeg) it depends on — all produced under the build dir.
find "${BUILDDIR}" -name '*.a' -type f -exec cp -f {} "${DEST}/lib/" \;
# The prebuilt dependency archives from the sysroot.
find "${SYSROOT_PREFIX}/lib" -maxdepth 1 -name '*.a' -type f -exec cp -f {} "${DEST}/lib/" \; 2>/dev/null || true

echo "Staged engine + deps into ${DEST}"

# Emit the xcconfig the Xcode project includes: header + library search paths,
# the bridging header, and the full static link line. The dependency link flags
# are computed from the sysroot's .pc files so they stay in sync with whatever
# the sysroot actually provides.
mkdir -p "${VENDOR}"
XCCONFIG="${VENDOR}/nordstjernen.xcconfig"

DEP_MODULES="glib-2.0 gobject-2.0 gio-2.0 gmodule-2.0 cairo pango pangocairo \
libcurl libcrypto uchardet libpsl sqlite3 libwebp libwebpdemux"
DEP_LIBS="$(PKG_CONFIG_LIBDIR="${SYSROOT_PREFIX}/lib/pkgconfig" \
  pkg-config --libs --static ${DEP_MODULES} 2>/dev/null || true)"

# Every staged in-tree archive becomes a -l flag (lib<name>.a -> -l<name>).
ENGINE_LIBS=""
for a in "${DEST}"/lib/lib*.a; do
  [ -e "${a}" ] || continue
  base="$(basename "${a}")"; base="${base#lib}"; base="${base%.a}"
  ENGINE_LIBS="${ENGINE_LIBS} -l${base}"
done

cat > "${XCCONFIG}" <<EOF
// Auto-generated by ios/scripts/build-engine.sh — DO NOT EDIT BY HAND.
// Regenerated per platform; commit is optional (this is a build artifact).
HEADER_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/../../src \$(SRCROOT)/Bridge \$(SRCROOT)/vendor/${PLATFORM}/include
LIBRARY_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/vendor/${PLATFORM}/lib
OTHER_LDFLAGS = \$(inherited)${ENGINE_LIBS} ${DEP_LIBS} -lc++ -liconv -lresolv -lz -framework Foundation -framework UIKit -framework CoreGraphics -framework CoreText -framework CoreFoundation -framework Security -framework CFNetwork -framework ImageIO -framework SystemConfiguration
EOF

echo "Wrote ${XCCONFIG}"
echo "Done: libnordstjernen for ${PLATFORM} staged under ${DEST}"
