#!/usr/bin/env python3
"""Generate src/lexbor/source/lexbor/unicode/idna_validity.c from the UCD.

Reads DerivedJoiningType.txt, DerivedBidiClass.txt, DerivedCombiningClass.txt
and DerivedGeneralCategory.txt from a UCD directory (default
/usr/share/unicode, Debian package unicode-data) and emits a compact
range table with the properties UTS #46 validity criteria need:
joining type (CONTEXTJ), bidi class (RFC 5893), virama (ccc 9) and
general-category mark.
"""
import re
import sys

UCD = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/unicode'
OUT = sys.argv[2] if len(sys.argv) > 2 else \
    'src/lexbor/source/lexbor/unicode/idna_validity.c'

MAX = 0x110000

JOIN = {'T': 1, 'L': 2, 'R': 3, 'D': 4}
BIDI = {'L': 1, 'R': 2, 'AL': 3, 'AN': 4, 'EN': 5, 'ES': 6, 'CS': 7,
        'ET': 8, 'ON': 9, 'BN': 10, 'NSM': 11}
VIRAMA = 1 << 8
MARK = 1 << 9

props = [0] * MAX

def parse(path):
    for line in open(path):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        rng, value = [x.strip() for x in line.split(';')[:2]]
        if '..' in rng:
            lo, hi = [int(x, 16) for x in rng.split('..')]
        else:
            lo = hi = int(rng, 16)
        yield lo, hi, value

for lo, hi, v in parse(UCD + '/extracted/DerivedJoiningType.txt'):
    if v in JOIN:
        for cp in range(lo, hi + 1):
            props[cp] |= JOIN[v] << 4

for lo, hi, v in parse(UCD + '/extracted/DerivedBidiClass.txt'):
    if v in BIDI:
        for cp in range(lo, hi + 1):
            props[cp] |= BIDI[v]

for lo, hi, v in parse(UCD + '/extracted/DerivedCombiningClass.txt'):
    if v == '9':
        for cp in range(lo, hi + 1):
            props[cp] |= VIRAMA

for lo, hi, v in parse(UCD + '/extracted/DerivedGeneralCategory.txt'):
    if v in ('Mn', 'Mc', 'Me'):
        for cp in range(lo, hi + 1):
            props[cp] |= MARK

ranges = []
cp = 0
while cp < MAX:
    if props[cp]:
        start = cp
        val = props[cp]
        while cp < MAX and props[cp] == val:
            cp += 1
        ranges.append((start, cp - 1, val))
    else:
        cp += 1

with open(OUT, 'w') as f:
    f.write("/*\n * idna_validity.c — Unicode property ranges for UTS #46"
            " validity criteria.\n * Generated by scripts/gen-idna-validity.py"
            " from the UCD; do not edit.\n */\n\n")
    f.write('#include "lexbor/unicode/idna.h"\n\n')
    f.write("typedef struct {\n"
            "    uint32_t start;\n"
            "    uint32_t end;\n"
            "    uint16_t props;\n"
            "}\nlxb_unicode_idna_validity_range_t;\n\n")
    f.write("static const lxb_unicode_idna_validity_range_t "
            "lxb_unicode_idna_validity_ranges[%d] = {\n" % len(ranges))
    for start, end, val in ranges:
        f.write("    {0x%05X, 0x%05X, 0x%03X},\n" % (start, end, val))
    f.write("};\n\n")
    f.write("""uint16_t
lxb_unicode_idna_validity_props(lxb_codepoint_t cp)
{
    size_t low, mid, high;
    const lxb_unicode_idna_validity_range_t *r;

    low = 0;
    high = sizeof(lxb_unicode_idna_validity_ranges)
           / sizeof(lxb_unicode_idna_validity_ranges[0]);

    while (low < high) {
        mid = low + (high - low) / 2;
        r = &lxb_unicode_idna_validity_ranges[mid];

        if (cp < r->start) {
            high = mid;
        }
        else if (cp > r->end) {
            low = mid + 1;
        }
        else {
            return r->props;
        }
    }

    return 0;
}
""")

print('%s: %d ranges' % (OUT, len(ranges)), file=sys.stderr)
